// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/javito2003/shortener_url/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// LinkCache is an autogenerated mock type for the LinkCache type
type LinkCache struct {
	mock.Mock
}

// FindByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *LinkCache) FindByShortCode(ctx context.Context, shortCode string) (*domain.Link, bool, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByShortCode")
	}

	var r0 *domain.Link
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, bool, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = rf(ctx, shortCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, shortCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByUrl provides a mock function with given fields: ctx, url
func (_m *LinkCache) GetByUrl(ctx context.Context, url string) (*domain.Link, bool, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetByUrl")
	}

	var r0 *domain.Link
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, bool, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, url)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IncrementClickCount provides a mock function with given fields: ctx, linkId
func (_m *LinkCache) IncrementClickCount(ctx context.Context, linkId string) error {
	ret := _m.Called(ctx, linkId)

	if len(ret) == 0 {
		panic("no return value specified for IncrementClickCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, linkId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, link
func (_m *LinkCache) Save(ctx context.Context, link *domain.Link) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Link) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLinkCache creates a new instance of LinkCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkCache {
	mock := &LinkCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
