name: CI

on: [push]

jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' || github.ref_name == 'development'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch

      - name: Set enviroment name
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == "development" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          elif [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          fi

      - name: Build the Docker image
        run: docker build -t shortener_url .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Push to DigitalOcean Container Registry
        run: |
          doctl registry login
          docker tag shortener_url registry.digitalocean.com/javito/shortener_url:${{ env.ENV_NAME }}
          docker push registry.digitalocean.com/javito/shortener_url:${{ env.ENV_NAME }}
