name: CI

on: [push]

jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' || github.ref_name == 'development'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch

      - name: Set enviroment name
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == "development" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          elif [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          fi

      - name: Login into Digital Ocean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          password: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/shortener-url:${{ env.ENV_NAME }}